### ISSUE TITLE
Metadata in TanzuNet product needs changing after release

### ISSUE THREAD

**Issue by gcheadle-vmware** [carvel-dev/release-scripts#11]
Not sure if this is the correct repo to report this issue.

When I released ytt v0.40.0, the pipeline that created the TanzuNet product had information filled in that is considered incorrect by the [hackMD release process doc](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Manual-Product-Creation-on-TanzuNet-FireFox-is-recommended-and-sign-in-is-in-LastPass). The metadata that needed changing was:
- populated "RELEASE NOTES URL", it was empty
- changed "RELEASE DATE" to two week from today, it was the date the pipeline ran

Relevant slack thread in #carvel-private slack channel (not linking to private channel)

**Comment by neil-hickey** [comment]
No longer releasing to tanzunet
