### ISSUE TITLE
Change keys used on automation

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/release-scripts#28]
Currently, we are using Dennis key to create commits on some of the automated workflows

<img width="665" alt="Screen Shot 2022-12-05 at 4 39 58 PM" src="https://user-images.githubusercontent.com/1826130/205758295-9caad1af-26a7-45bf-b6c3-27d0f9bc8c46.png">

We should try to use a different generic account.

**Comment by aaronshurley** [comment]
This will potentially be solved by https://github.com/vmware-tanzu-private/carvel-internal/issues/46

**Comment by neil-hickey** [comment]
hey @joaopapereira / @vmunishwar did we think this "got resolved" by the lastpass rotation or no?

**Comment by joaopapereira** [comment]
Yep going to close this
